api:
  url: "https://data.cityofnewyork.us/resource/erm2-nwe9.json"
  limit: 100

duckdb:
  database: "data/warehouse/nyc_311.duckdb"
  table: "raw_service_requests"
paths:
  raw_data: "data/raw/nyc_311_raw.json"
  processed_data: "data/processed/nyc_311_clean.parquet"